
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:

networks:
  scheisse.edu:
    external:
      name: net_test

services:

  explorerdb.scheisse.edu:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.scheisse.edu
    hostname: explorerdb.scheisse.edu
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - scheisse.edu

  explorer.scheisse.edu:
    image: hyperledger/explorer:latest
    container_name: explorer.scheisse.edu
    hostname: explorer.scheisse.edu
    environment:
      - DATABASE_HOST=explorerdb.scheisse.edu
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./config.json:/opt/explorer/app/platform/fabric/config.json
      - ./connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./organizations:/tmp/crypto
    ports:
      - 9999:8080
    depends_on:
      explorerdb.scheisse.edu:
        condition: service_healthy
    networks:
      - scheisse.edu
